version: '3.8'
services:
  notificacao-service:
    build: .
    container_name: notificacao-service
    ports:
      - "8082:8082"
    environment:
      - USERNAME_EMAIL=${USERNAME_EMAIL}
      - PASSWORD_EMAIL=${PASSWORD_EMAIL}
    networks:
      - minha-rede
networks:
  minha-rede:
    external: true

